# NOTE: DO NOT EDIT.
# Regenerate with: pnpm generate

from __future__ import annotations

from mosaic_spec._typing_compat import TypedDict


class CSSStyles(TypedDict, total=False, extra_items=str):
    accent_color: str
    align_content: str
    align_items: str
    align_self: str
    alignment_baseline: str
    all: str
    animation: str
    animation_composition: str
    animation_delay: str
    animation_direction: str
    animation_duration: str
    animation_fill_mode: str
    animation_iteration_count: str
    animation_name: str
    animation_play_state: str
    animation_timing_function: str
    appearance: str
    aspect_ratio: str
    backdrop_filter: str
    backface_visibility: str
    background: str
    background_attachment: str
    background_blend_mode: str
    background_clip: str
    background_color: str
    background_image: str
    background_origin: str
    background_position: str
    background_position_x: str
    background_position_y: str
    background_repeat: str
    background_size: str
    baseline_shift: str
    baseline_source: str
    block_size: str
    border: str
    border_block: str
    border_block_color: str
    border_block_end: str
    border_block_end_color: str
    border_block_end_style: str
    border_block_end_width: str
    border_block_start: str
    border_block_start_color: str
    border_block_start_style: str
    border_block_start_width: str
    border_block_style: str
    border_block_width: str
    border_bottom: str
    border_bottom_color: str
    border_bottom_left_radius: str
    border_bottom_right_radius: str
    border_bottom_style: str
    border_bottom_width: str
    border_collapse: str
    border_color: str
    border_end_end_radius: str
    border_end_start_radius: str
    border_image: str
    border_image_outset: str
    border_image_repeat: str
    border_image_slice: str
    border_image_source: str
    border_image_width: str
    border_inline: str
    border_inline_color: str
    border_inline_end: str
    border_inline_end_color: str
    border_inline_end_style: str
    border_inline_end_width: str
    border_inline_start: str
    border_inline_start_color: str
    border_inline_start_style: str
    border_inline_start_width: str
    border_inline_style: str
    border_inline_width: str
    border_left: str
    border_left_color: str
    border_left_style: str
    border_left_width: str
    border_radius: str
    border_right: str
    border_right_color: str
    border_right_style: str
    border_right_width: str
    border_spacing: str
    border_start_end_radius: str
    border_start_start_radius: str
    border_style: str
    border_top: str
    border_top_color: str
    border_top_left_radius: str
    border_top_right_radius: str
    border_top_style: str
    border_top_width: str
    border_width: str
    bottom: str
    box_decoration_break: str
    box_shadow: str
    box_sizing: str
    break_after: str
    break_before: str
    break_inside: str
    caption_side: str
    caret_color: str
    clear: str
    clip: str
    clip_path: str
    clip_rule: str
    color: str
    color_interpolation: str
    color_interpolation_filters: str
    color_scheme: str
    column_count: str
    column_fill: str
    column_gap: str
    column_rule: str
    column_rule_color: str
    column_rule_style: str
    column_rule_width: str
    column_span: str
    column_width: str
    columns: str
    contain: str
    contain_intrinsic_block_size: str
    contain_intrinsic_height: str
    contain_intrinsic_inline_size: str
    contain_intrinsic_size: str
    contain_intrinsic_width: str
    container: str
    container_name: str
    container_type: str
    content: str
    content_visibility: str
    counter_increment: str
    counter_reset: str
    counter_set: str
    css_float: str
    css_text: str
    cursor: str
    cx: str
    cy: str
    d: str
    direction: str
    display: str
    dominant_baseline: str
    empty_cells: str
    fill: str
    fill_opacity: str
    fill_rule: str
    filter: str
    flex: str
    flex_basis: str
    flex_direction: str
    flex_flow: str
    flex_grow: str
    flex_shrink: str
    flex_wrap: str
    float: str
    flood_color: str
    flood_opacity: str
    font: str
    font_family: str
    font_feature_settings: str
    font_kerning: str
    font_optical_sizing: str
    font_palette: str
    font_size: str
    font_size_adjust: str
    font_stretch: str
    font_style: str
    font_synthesis: str
    font_synthesis_small_caps: str
    font_synthesis_style: str
    font_synthesis_weight: str
    font_variant: str
    font_variant_alternates: str
    font_variant_caps: str
    font_variant_east_asian: str
    font_variant_ligatures: str
    font_variant_numeric: str
    font_variant_position: str
    font_variation_settings: str
    font_weight: str
    forced_color_adjust: str
    gap: str
    grid: str
    grid_area: str
    grid_auto_columns: str
    grid_auto_flow: str
    grid_auto_rows: str
    grid_column: str
    grid_column_end: str
    grid_column_gap: str
    grid_column_start: str
    grid_gap: str
    grid_row: str
    grid_row_end: str
    grid_row_gap: str
    grid_row_start: str
    grid_template: str
    grid_template_areas: str
    grid_template_columns: str
    grid_template_rows: str
    height: str
    hyphenate_character: str
    hyphenate_limit_chars: str
    hyphens: str
    image_orientation: str
    image_rendering: str
    inline_size: str
    inset: str
    inset_block: str
    inset_block_end: str
    inset_block_start: str
    inset_inline: str
    inset_inline_end: str
    inset_inline_start: str
    isolation: str
    justify_content: str
    justify_items: str
    justify_self: str
    left: str
    length: float
    letter_spacing: str
    lighting_color: str
    line_break: str
    line_height: str
    list_style: str
    list_style_image: str
    list_style_position: str
    list_style_type: str
    margin: str
    margin_block: str
    margin_block_end: str
    margin_block_start: str
    margin_bottom: str
    margin_inline: str
    margin_inline_end: str
    margin_inline_start: str
    margin_left: str
    margin_right: str
    margin_top: str
    marker: str
    marker_end: str
    marker_mid: str
    marker_start: str
    mask: str
    mask_clip: str
    mask_composite: str
    mask_image: str
    mask_mode: str
    mask_origin: str
    mask_position: str
    mask_repeat: str
    mask_size: str
    mask_type: str
    math_depth: str
    math_style: str
    max_block_size: str
    max_height: str
    max_inline_size: str
    max_width: str
    min_block_size: str
    min_height: str
    min_inline_size: str
    min_width: str
    mix_blend_mode: str
    object_fit: str
    object_position: str
    offset: str
    offset_anchor: str
    offset_distance: str
    offset_path: str
    offset_position: str
    offset_rotate: str
    opacity: str
    order: str
    orphans: str
    outline: str
    outline_color: str
    outline_offset: str
    outline_style: str
    outline_width: str
    overflow: str
    overflow_anchor: str
    overflow_block: str
    overflow_clip_margin: str
    overflow_inline: str
    overflow_wrap: str
    overflow_x: str
    overflow_y: str
    overscroll_behavior: str
    overscroll_behavior_block: str
    overscroll_behavior_inline: str
    overscroll_behavior_x: str
    overscroll_behavior_y: str
    padding: str
    padding_block: str
    padding_block_end: str
    padding_block_start: str
    padding_bottom: str
    padding_inline: str
    padding_inline_end: str
    padding_inline_start: str
    padding_left: str
    padding_right: str
    padding_top: str
    page: str
    page_break_after: str
    page_break_before: str
    page_break_inside: str
    paint_order: str
    perspective: str
    perspective_origin: str
    place_content: str
    place_items: str
    place_self: str
    pointer_events: str
    position: str
    print_color_adjust: str
    quotes: str
    r: str
    resize: str
    right: str
    rotate: str
    row_gap: str
    ruby_align: str
    ruby_position: str
    rx: str
    ry: str
    scale: str
    scroll_behavior: str
    scroll_margin: str
    scroll_margin_block: str
    scroll_margin_block_end: str
    scroll_margin_block_start: str
    scroll_margin_bottom: str
    scroll_margin_inline: str
    scroll_margin_inline_end: str
    scroll_margin_inline_start: str
    scroll_margin_left: str
    scroll_margin_right: str
    scroll_margin_top: str
    scroll_padding: str
    scroll_padding_block: str
    scroll_padding_block_end: str
    scroll_padding_block_start: str
    scroll_padding_bottom: str
    scroll_padding_inline: str
    scroll_padding_inline_end: str
    scroll_padding_inline_start: str
    scroll_padding_left: str
    scroll_padding_right: str
    scroll_padding_top: str
    scroll_snap_align: str
    scroll_snap_stop: str
    scroll_snap_type: str
    scrollbar_color: str
    scrollbar_gutter: str
    scrollbar_width: str
    shape_image_threshold: str
    shape_margin: str
    shape_outside: str
    shape_rendering: str
    stop_color: str
    stop_opacity: str
    stroke: str
    stroke_dasharray: str
    stroke_dashoffset: str
    stroke_linecap: str
    stroke_linejoin: str
    stroke_miterlimit: str
    stroke_opacity: str
    stroke_width: str
    tab_size: str
    table_layout: str
    text_align: str
    text_align_last: str
    text_anchor: str
    text_box: str
    text_box_edge: str
    text_box_trim: str
    text_combine_upright: str
    text_decoration: str
    text_decoration_color: str
    text_decoration_line: str
    text_decoration_skip_ink: str
    text_decoration_style: str
    text_decoration_thickness: str
    text_emphasis: str
    text_emphasis_color: str
    text_emphasis_position: str
    text_emphasis_style: str
    text_indent: str
    text_orientation: str
    text_overflow: str
    text_rendering: str
    text_shadow: str
    text_transform: str
    text_underline_offset: str
    text_underline_position: str
    text_wrap: str
    text_wrap_mode: str
    text_wrap_style: str
    top: str
    touch_action: str
    transform: str
    transform_box: str
    transform_origin: str
    transform_style: str
    transition: str
    transition_behavior: str
    transition_delay: str
    transition_duration: str
    transition_property: str
    transition_timing_function: str
    translate: str
    unicode_bidi: str
    user_select: str
    vector_effect: str
    vertical_align: str
    view_transition_class: str
    view_transition_name: str
    visibility: str
    webkit_align_content: str
    webkit_align_items: str
    webkit_align_self: str
    webkit_animation: str
    webkit_animation_delay: str
    webkit_animation_direction: str
    webkit_animation_duration: str
    webkit_animation_fill_mode: str
    webkit_animation_iteration_count: str
    webkit_animation_name: str
    webkit_animation_play_state: str
    webkit_animation_timing_function: str
    webkit_appearance: str
    webkit_backface_visibility: str
    webkit_background_clip: str
    webkit_background_origin: str
    webkit_background_size: str
    webkit_border_bottom_left_radius: str
    webkit_border_bottom_right_radius: str
    webkit_border_radius: str
    webkit_border_top_left_radius: str
    webkit_border_top_right_radius: str
    webkit_box_align: str
    webkit_box_flex: str
    webkit_box_ordinal_group: str
    webkit_box_orient: str
    webkit_box_pack: str
    webkit_box_shadow: str
    webkit_box_sizing: str
    webkit_filter: str
    webkit_flex: str
    webkit_flex_basis: str
    webkit_flex_direction: str
    webkit_flex_flow: str
    webkit_flex_grow: str
    webkit_flex_shrink: str
    webkit_flex_wrap: str
    webkit_justify_content: str
    webkit_line_clamp: str
    webkit_mask: str
    webkit_mask_box_image: str
    webkit_mask_box_image_outset: str
    webkit_mask_box_image_repeat: str
    webkit_mask_box_image_slice: str
    webkit_mask_box_image_source: str
    webkit_mask_box_image_width: str
    webkit_mask_clip: str
    webkit_mask_composite: str
    webkit_mask_image: str
    webkit_mask_origin: str
    webkit_mask_position: str
    webkit_mask_repeat: str
    webkit_mask_size: str
    webkit_order: str
    webkit_perspective: str
    webkit_perspective_origin: str
    webkit_text_fill_color: str
    webkit_text_size_adjust: str
    webkit_text_stroke: str
    webkit_text_stroke_color: str
    webkit_text_stroke_width: str
    webkit_transform: str
    webkit_transform_origin: str
    webkit_transform_style: str
    webkit_transition: str
    webkit_transition_delay: str
    webkit_transition_duration: str
    webkit_transition_property: str
    webkit_transition_timing_function: str
    webkit_user_select: str
    white_space: str
    white_space_collapse: str
    widows: str
    width: str
    will_change: str
    word_break: str
    word_spacing: str
    word_wrap: str
    writing_mode: str
    x: str
    y: str
    z_index: str
    zoom: str
