from __future__ import annotations


# NOTE: `_gen.interactors` is pretty close to usable already
# - a few `ParamRef`s need replacing
# - base options classes can be replicated
def highlight() -> None: ...


# NOTE: `channels: Required[Sequence[str]]` should use `_gen.typing.ChannelName`
def region() -> None: ...


# NOTE: `channels: Sequence[str]` should use `_gen.typing.ChannelName`
def nearest_x() -> None: ...
def nearest_y() -> None: ...


# NOTE: All same options, just select differs
def pan() -> None: ...
def pan_x() -> None: ...
def pan_y() -> None: ...
def pan_zoom() -> None: ...
def pan_zoom_x() -> None: ...
def pan_zoom_y() -> None: ...


# NOTE: `channels: Required[Sequence[str]]` should use `_gen.typing.ChannelName`
def toggle() -> None: ...


def toggle_color() -> None: ...
def toggle_x() -> None: ...
def toggle_y() -> None: ...
def interval_x() -> None: ...
def interval_y() -> None: ...
def interval_xy() -> None: ...
