#:schema file://./mosaic-spec-toml-schema.json

[convert]
sources = [{ id = "mosaic", path = "../../spec/dist/mosaic-schema.json" }]

[convert.to_mlir]
ref_unwrap = { Curve = { description = "outer" } }

[[convert.to_mlir.actions]]
action                         = "remove"
scope.include.definition.names = ["Spec"]
scope.over                     = "definitions"

[[convert.to_mlir.actions]]
action                         = "new-tree"
id                             = "params"
scope.include.definition.names = ["ParamDefinition"]
scope.over                     = "descendants"
scope.ref_follow_depth         = 5

[[convert.to_mlir.actions]]
action                         = "new-tree"
id                             = "typing"
scope.include.id               = ["mosaic"]
# TODO: `ColorScheme` Needs to remove 1x `Record<never, never>`
scope.include.definition.names = [
  "ChannelDomainValue",
  "ColorScaleType",
  "ColorScheme",
  "ContinuousScaleType",
  "Curve",
  "DiscreteScaleType",
  "Fixed",
  "FrameAnchor",
  "GridInterpolate",
  "Interpolate",
  "Interval",
  "LabelArrow",
  "MarkerName",
  "PositionScaleType",
  "ProjectionName",
  "Reducer",
  "ScaleName",
  "SelectFilter",
  "StackOffset",
  "StackOrder",
  "SymbolType",
  "TipPointer",
  "VectorShape",
]
scope.over                     = "descendants"
scope.ref_follow_depth         = 2

# TODO: `SpecDeduplicate`

[[convert.to_mlir.actions]]
action                         = "new-tree"
id                             = "css_styles"
scope.include.id               = ["mosaic"]
scope.include.definition.names = ["CSSStyles"]
scope.over                     = "definitions"

[[convert.to_mlir.actions]]
action                         = "new-tree"
id                             = "interactors"
scope.include.id               = ["mosaic"]
scope.include.definition.names = ["PlotInteractor"]
scope.over                     = "descendants"
scope.ref_follow_depth         = 2

[[convert.to_mlir.actions]]
action                         = "new-tree"
id                             = "transform"
scope.include.id               = ["mosaic"]
scope.include.definition.names = ["Transform", "IntervalTransform"]
scope.over                     = "descendants"
scope.ref_follow_depth         = 10

[[convert.to_mlir.actions]]
action                         = "new-tree"
id                             = "data"
scope.include.id               = ["mosaic"]
scope.include.definition.names = ["DataDefinition"]
scope.over                     = "descendants"
scope.ref_follow_depth         = 1

[[convert.to_mlir.actions]]
action                         = "new-tree"
id                             = "expression"
scope.include.id               = ["mosaic"]
scope.include.definition.names = ["AggregateExpression", "SQLExpression"]
scope.over                     = "definitions"

[[convert.to_mlir.actions]]
action                         = "new-tree"
id                             = "plot_from"
scope.include.id               = ["mosaic"]
scope.include.definition.names = ["PlotMarkData"]
scope.over                     = "descendants"
scope.ref_follow_depth         = 1

[[convert.to_mlir.actions]]
action                         = "new-tree"
id                             = "marks"
scope.include.id               = ["mosaic"]
scope.include.definition.names = ["PlotMark"]
scope.over                     = "descendants"
scope.ref_follow_depth         = 5

[[convert.to_mlir.actions]]
action                         = "new-tree"
id                             = "plot_legend"
scope.include.id               = ["mosaic"]
scope.include.definition.names = ["Legend", "PlotLegend"]
scope.over                     = "definitions"

[[convert.to_mlir.actions]]
action                         = "new-tree"
id                             = "plot"
scope.include.id               = ["mosaic"]
scope.include.definition.names = ["PlotAttributes", "Plot"]
scope.over                     = "definitions"

# TODO: `_recursive_replace` -> `KEYS_REPLACE`
# - Should be handled in a later stage, where identifiers need to be valid python
