from collections.abc import ItemsView, Iterable, Iterator, KeysView, Mapping, ValuesView
from typing import Any, Self, final, overload

type _IntoMap[K, V] = Mapping[K, V] | Iterable[tuple[K, V]]

@final
class HashTrieMap[K, V](Mapping[K, V]):
    """An immutable, persistent mapping.

    ## Important
    Methods that *look like* mutation, return a new object with shared data.

    Args:
        iterable: Initial entries as a mapping or an iterable over entry pairs.
        **kwds: Keywords mapping keys to values.
            `**kwds` will override `iterable` **and** change the order of the new mapping.

    ## Notes
    Fixed typing, docs and aliasing around [rpds.HashTrieMap].

    *This is the documentation for* [`rpds::map::hash_trie_map`]

    A persistent map with structural sharing.
    This implementation uses a [hash array mapped trie].

    [rpds.HashTrieMap]: https://rpds.readthedocs.io/en/latest/api/#rpds.HashTrieMap
    [`rpds::map::hash_trie_map`]: https://docs.rs/rpds/latest/rpds/map/hash_trie_map/struct.HashTrieMap.html
    [hash array mapped trie]: https://en.wikipedia.org/wiki/Hash_array_mapped_trie
    """
    def items(self) -> ItemsView[K, V]: ...
    def keys(self) -> KeysView[K]: ...
    def values(self) -> ValuesView[V]: ...
    def __getitem__(self, key: object) -> V: ...
    def __iter__(self) -> Iterator[K]: ...
    def __len__(self) -> int: ...

    ##
    @overload
    def update[K2, V2](self, *maps: _IntoMap[K2, V2]) -> HashTrieMap[K | K2, V | V2]:
        """Return a new mapping, with changes from `*maps`, `**kwds`.

        Args:
            *maps: One *or more* positional iterables/mappings.
            **kwds: Keywords mapping keys to values.
                `**kwds` will override `iterable` **and** change the order of the new mapping.

        ## Important
        Despite the name, this is not the same as [`MutableMapping.update`]

        [`MutableMapping.update`]: https://github.com/python/typeshed/blob/bc016545988403f13b2dd9b56e88b931683c80b1/stdlib/typing.pyi#L854-L883
        """
    @overload
    def update[V2](self, **kwds: V2) -> HashTrieMap[K | str, V | V2]: ...
    @overload
    def update[K2, V2](
        self, *maps: *tuple[_IntoMap[K2, V2], *tuple[_IntoMap[K2, V2]]], **kwds: V2
    ) -> HashTrieMap[K | K2 | str, V | V2]: ...

    # NOTE: `dict`-ish methods
    @overload
    def __init__(self, /) -> None: ...
    @overload
    def __init__[K2, V2](self: HashTrieMap[K2, V2], iterable: _IntoMap[K2, V2], /) -> None: ...
    @overload
    def __init__[V2](
        self: HashTrieMap[str, V2], iterable: _IntoMap[str, V2] = (), /, **kwds: V2
    ) -> None: ...
    @overload
    def __init__[K2, V2](
        self: HashTrieMap[K2 | str, V2], iterable: _IntoMap[K2, V2], /, **kwds: V2
    ) -> None: ...

    ##
    @classmethod
    @overload
    def fromkeys[K2](
        cls, iterable: Iterable[K2], value: None = None, /
    ) -> HashTrieMap[K2, Any | None]:
        """Create a new dictionary with keys from iterable and values set to value."""
    @classmethod
    @overload
    def fromkeys[K2, V2](cls, iterable: Iterable[K2], value: V2, /) -> HashTrieMap[K2, V2]: ...

    # NOTE: Non-mapping methods
    @classmethod
    def convert[K2, V2](cls, value: _IntoMap[K2, V2], /) -> HashTrieMap[K2, V2]: ...
    def discard(self, key: K) -> Self: ...
    def remove(self, key: K) -> Self: ...
    def insert[K2, V2](self, key: K2, val: V2) -> HashTrieMap[K | K2, V | V2]: ...

class HashTrieSet[T](frozenset[T]):
    def __init__(self, value: Iterable[T] = ()) -> None: ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...
    def discard(self, value: T) -> HashTrieSet[T]: ...
    def remove(self, value: T) -> HashTrieSet[T]: ...
    def insert(self, value: T) -> HashTrieSet[T]: ...
    def update(self, *args: Iterable[T]) -> HashTrieSet[T]: ...

class List[T](Iterable[T]):
    def __init__(self, value: Iterable[T] = (), *more: T) -> None: ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...
    def push_front(self, value: T) -> List[T]: ...
    def drop_first(self) -> List[T]: ...

class Queue[T](Iterable[T]):
    def __init__(self, value: Iterable[T] = (), *more: T) -> None: ...
    def __iter__(self) -> Iterator[T]: ...
    def __len__(self) -> int: ...
    def enqueue(self, value: T) -> Queue[T]: ...
    def dequeue(self, value: T) -> Queue[T]: ...
    @property
    def is_empty(self) -> T: ...
    @property
    def peek(self) -> T: ...
